apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-pihole-configmap
  namespace: apps
data:
  02-custom-dns.conf: |
    # address=/${cluster_domain}/192.168.0.122  # Wildcard DNS handled by GoDaddy