apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  namespace: apps
spec:
  capacity:
    storage: 7Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/config
